### ISSUE TITLE
Botoes não funcionam na conversa com André

### ISSUE THREAD

**Issue by joaopedrosgs** [LOA-SEAD/a-era-inclusiva#30]
Frase inicial de André “sempre que precisar que a mensagem seja repetida Enter ou Barra de Espaço para nossa conversa continuar” está incompleta. Podemos substituir para Sempre que precisar que a mensagem seja repetida aperte Q. Pressione Enter ou Barra de Espaço para nossa conversa continuar.

![image](https://user-images.githubusercontent.com/16986475/58956269-4da31400-8774-11e9-9447-a9ad82ae3c1f.png)

**Comment by miguelsott** [comment]
Fixed with 161323074071e7d98f671a5e88b2db9a325b8b68

**Comment by miguelsott** [comment]
Fixed with 161323074071e7d98f671a5e88b2db9a325b8b68
