### ISSUE TITLE
Consistencia nos botoes da sala dos professores

### ISSUE THREAD

**Issue by joaopedrosgs** [LOA-SEAD/a-era-inclusiva#31]
Mover botoes para um lado só e manter consistência com a sala da biblioteca

**Comment by rogerbordini** [comment]
algo assim: 

![Untitled](https://user-images.githubusercontent.com/7660777/60451513-811a7680-9c2c-11e9-90e8-37ef61cc76ce.jpg)

**Comment by joaopedrosgs** [comment]
Resolvido pelo #44
