### ISSUE TITLE
Balão da demanda na cabeça do aluno

### ISSUE THREAD

**Issue by joaopedrosgs** [LOA-SEAD/a-era-inclusiva#33]
Quando uma demanda aparecer, fazer com que o balão de exclamação apareça também sob a cabeça do(a) respectivo(a) aluno(a) na sala para que o jogador veja de quem é aquela demanda. A mesma coisa pode acontecer toda vez que o jogador selecionar a demanda na lista à esquerda. Esses balões estão disponíveis nesta pasta no Drive

**Comment by rogerbordini** [comment]
Também é possível diminuir um pouco o balão de pensamento da professora? Ele está escondendo o rosto dela:

![Untitled](https://user-images.githubusercontent.com/7660777/60441170-bb791900-9c16-11e9-8afa-13872fe7cf7a.jpg)

**Comment by joaopedrosgs** [comment]
> Também é possível diminuir um pouco o balão de pensamento da professora? Ele está escondendo o rosto dela:
> 
> ![Untitled](https://user-images.githubusercontent.com/7660777/60441170-bb791900-9c16-11e9-8afa-13872fe7cf7a.jpg)

Arrumei isso agora

**Comment by joaopedrosgs** [comment]
Resolvido pelo #45
