### ISSUE TITLE
Feedback do HTPI inexistente

### ISSUE THREAD

**Issue by joaopedrosgs** [LOA-SEAD/a-era-inclusiva#36]
No HTPI faltou inserir as telas com o feedback das decisões do jogador. O feedback relacionado à cada demanda está neste documento de Implementação das Fases (http://bit.ly/2WMIa9d) os novos PSD com as telas de Feedback estão aqui: https://drive.google.com/file/d/13bxa4qafopHQU09-caSAqXjDcPJ8a-sE/view?usp=sharing

**Comment by rogerbordini** [comment]
Inclusão da demanda do aluno no texto de feedback, para que o jogador se lembre qual foi a ação escolhida para aquela situação. Ex:

![tela_PLANO_AULA_parte02(2)-(1)](https://user-images.githubusercontent.com/7660777/60464266-57724700-9c4e-11e9-8dba-cc54e71f7d5a.jpg)

**Comment by joaopedrosgs** [comment]
adicionado, podem será refeito
