### ISSUE TITLE
Sem audio

### ISSUE THREAD

**Issue by joaopedrosgs** [LOA-SEAD/a-era-inclusiva#38]
Estou adicionando os arquivos de áudio que o Roger disponibilizou
O progresso pode ser visto aqui: https://github.com/joaopedrosgs/a-era-inclusiva/tree/Som

**Comment by joaopedrosgs** [comment]
Adicionado sons em todas as telas, no entanto, ainda faltam alguns efeitos

**Comment by rogerbordini** [comment]
- Incluir o som de sinal indicando o final a aula.

**Comment by miguelsott** [comment]
Continuado na issue #41
