### ISSUE TITLE
Ajustes Áudios 🔉

### ISSUE THREAD

**Issue by rogerbordini** [LOA-SEAD/a-era-inclusiva#41]
- [x] Diminuir entre 30%  e 50% o volume das ambiências sonoras (corredor e sala de aula) para que funcionem apenas como planos de fundo mesmo. Deixar esse som recorrente num volume alto pode irritar o jogador, sem contar que ainda teremos as músicas no futuro;
- [x] Retirar ambiência sonora de sala de aula no momento em que o jogado estiver acessando o tablet. Provavelmente nesse instante colocaremos uma música de fundo também;
- [x] Incluir possibilidade de desativar/ativar efeitos sonoros/música e ajustes de volume;
- [x] Sons de interação com os botões do menu (quando passa o mouse em cima do botão e quando clica) parecem que não estão lateralizados (esquerda ou direita); 
- [x] Na sala de aula, os botões referentes às ações pedagógicas (à direita) também estão sem sons para quando o ponteiro do mouse passa em cima deles;
- [x] Incluir o som de sinal (http://bit.ly/2x74pZ5) para indicar o início da aula (para quando o jogador terminar de preparar o HTPC, ao clicar no sinal de check no tablet) e para quando o tempo esgotar e/ou a última demanda for resolvida na Sala de Aula; 
- [x] Quando o jogador clica pra entrar numa sala, tocar este som (http://bit.ly/2Fsx2UU) e quando ele sai dela (botão de voltar), tocar este som (http://bit.ly/2Y9ayjl). Editei esses sons porque os anteriores estavam muito agressivos e com ruido.

**Comment by joaopedrosgs** [comment]
Resolvi alguns desses, falta incluir o som do fim da aula, retirar ambiência quando abre o tablet e adicionar possibilidade de desativar sons

**Comment by joaopedrosgs** [comment]
Resolvido
