### ISSUE TITLE
Mover Power UP

### ISSUE THREAD

**Issue by joaopedrosgs** [LOA-SEAD/a-era-inclusiva#42]
Mover os power ups para a barra da direita

**Comment by rogerbordini** [comment]
Ficaria algo assim:
![photo_2019-06-28_23-32-59](https://user-images.githubusercontent.com/7660777/60372524-2222ea80-99fd-11e9-89b2-b24469994311.jpg)
![photo_2019-06-28_21-14-47](https://user-images.githubusercontent.com/7660777/60372525-2222ea80-99fd-11e9-947c-79ddf9df8394.jpg)

**Comment by rogerbordini** [comment]
Só que daí os 3 power-ups apareceriam listado à direita

**Comment by joaopedrosgs** [comment]
Implementado
