### ISSUE TITLE
Implementação Sala de RM

### ISSUE THREAD

**Issue by rogerbordini** [LOA-SEAD/a-era-inclusiva#43]
O documento com o conteúdo que será apresentado nesta sala está nesse link: http://bit.ly/2XqvpOs . Os recursos estão agrupados em 4 categorias e suas descrições poderão ser apresentados por meio do próprio balão de diálogo da personagem.

A interface desta sala respeitará a mesma consistência de botões utilizada nas salas já implementadas. Exemplo: 

![Untitled](https://user-images.githubusercontent.com/7660777/60452728-7f05e700-9c2f-11e9-8623-4011828ad35d.jpg)

**Comment by joaopedrosgs** [comment]
Implementada
