### ISSUE TITLE
Ajustes dos áudios

### ISSUE THREAD

**Issue by rogerbordini** [LOA-SEAD/a-era-inclusiva#51]
- [x] Efeitos sonoros do Menu Inicial parecem estar invertidos quando escutados com fones (botões estão na direita e sons saem na esquerda);
- [x] Sala de RM está sem ambiência sonora de escola;
- [x] Ainda na Sala RM, os efeitos sonoros dos botões da direita tocam do lado esquerdo do fone;
- [x] No Plano de Aula, os efeitos sonoros que tocam ao passar o mouse em cima dos botões não estão lateralizados (esquerda ou direito) mas somente centralizados;
- [x] Na Sala de Aula, ao passar o mouse sobre as demandas dos alunos, não há efeito sonoro. Também há problema dos efeitos sonoros estarem tocando do lado errado do fone quando alguns botões são selecionados;

**Comment by joaopedrosgs** [comment]
Tudo resolvido
