### ISSUE TITLE
Lista de Ajustes para gerar a versão final (ATÉ 06/11)

### ISSUE THREAD

**Issue by rogerbordini** [LOA-SEAD/a-era-inclusiva#53]
- [x]  **[URGENTE]** Verificar se todos os áudios estão corretamente lateralizados. Testar tela por tela para ver se os efeitos sonoros estão tocando ao passar o mouse nos botões laterais (ex: botão lado direito toca no lado direito do fone). Em algumas telas, como Biblioteca e Sala RM, esse problema ainda persiste;
- [x]  **[URGENTE]** Colocar as 3 músicas do Suki no jogo (Pasta do Drive: [http://tiny.cc/yxy7ez](http://tiny.cc/yxy7ez)): **ideia 1** para a tela de título; **ideia 4** para todas as salas da escola (exceto sala de aula); e **ideia 5** para interação no tablet (Plano de Aula e HTPI);
- [x]  **[URGENTE]** Inserir todos os conteúdos na Biblioteca e Sala de RM. Documento com os conteúdos: [http://tiny.cc/k3y7ez](http://tiny.cc/k3y7ez). Se algo estiver faltando ou se tiverem dúvida, me procurem;
- [x]  Ao entrar no menu de configurações para ajustar os áudios, mudar os nomes para "Música" e "Efeitos Sonoros". Ex:

![image](https://user-images.githubusercontent.com/7660777/67624478-5cfc2a00-f807-11e9-9041-9e4481f5ff89.png)

- [x]  Verificar se os pontos dos acertos e erros na Sala de Aula estão atualizados de acordo com essa tabela revisada pela Josi (item 2): [http://tiny.cc/nmz7ez](http://tiny.cc/nmz7ez). Também reduzimos o número de ações pedagógicas disponíveis para serem selecionadas no Plano de Aula e HTPI (ver a tabela do item 3). Assim a lista ficará menor.
- [x]  Colocar os botões das ações pedagógicas e suas respectivas categorias em cores diferentes, assim fica fácil de identificá-las e memorizá-las, principalmente quando o jogador estiver as selecionando na lista do HTPI;
- [x] Se for possível, inserir Power-Ups com seu sistema de pontuação funcionando corretamente -> 1) **Elogiar a Classe**, custa 50 pts e ​congela o nível de satisfação da classe em 30 segundos; 2) **Ajuda do Estagiário,** custa 100 e aumenta o intervalo de tempo entre o aparecimento das demandas e; 3) **Resposta Certa**, custa 150 pts e exibe a melhor ação a ser tomada para uma demanda específica.
- [x]  Exportar o jogo para as versões 32 e 64 bits.

____

Acréscimos a serem feitos após 06/11:
- [ ] Implementar sistema de Upgrades da Escola (item 3 do doc a seguir): http://tiny.cc/hbm9ez

**Comment by joaopedrosgs** [comment]
Sobre os conteudos da biblioteca, acho que alguns livros vão aumentar MUITO o tamanho do projeto, sera q tem algum problema?
Alias, podemos upar no nosso repositório esses livros?

edit 1: Como pdf abrem no leitor externo, acho que vou só colocar um link pra eles

**Comment by miguelsott** [comment]
Isso, na verdade, é um problema sério a se considerar. No contexto do jogo, acho que se houvesse um pdf de livro completo, o jogador dificilmente iria parar para lê-lo durante o jogo. E talvez ele pegasse uma cópia desse pdf para depois. 
Mais perigoso é essa questão da licença. A gente não pode permitir que sejam colocados PDFs que gerariam algum problema legal, né.

**Comment by joaopedrosgs** [comment]
Tudo resolvido
